version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/node:12.18.4
    working_directory: ~/PruebaCircleCI
    steps:
      - checkout
      - run: cd PruebaCircleCI/backend
      - run: npm install --save
      - run: npm test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
