version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/node:10
  steps:
    - checkout
    - run: cd backend
    - run:
        name: install npm dependencies
      command: |
        npm install
    - run:
      name: run test
      command: |
        npm test
workflows:
  build_test:
    jobs:
      - run_test
