version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - run:
        command: |
          cd backend
          npm install --save
          npm test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
