version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - run:
          command: cd backend
      - run: npm install
      - run: npm test

workflows:
  jobs:
    - build
